before:
  hooks:
    - go mod download
builds:
  -
    main: ./cmd/main.go
    ldflags:
      - -s -w -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - freebsd
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
archives:
  -
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    format: binary
    files:
      - none*
checksum:
  name_template: 'checksums.txt'
