name: release

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      -
        name: Set TAG_NAME
        run: |
          echo "##[set-env name=TAG_NAME;]$(cat $GITHUB_EVENT_PATH | jq -r .ref | awk -F '/' '{print $3}')"
      -
        name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.12.4
      -
        name: Set GOPATH
        # temporary fix (see https://github.com/actions/setup-go/issues/14)
        run: |
          echo "##[set-env name=GOPATH;]$(dirname $GITHUB_WORKSPACE)"
          echo "##[add-path]$(dirname $GITHUB_WORKSPACE)/bin"
        shell: bash
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Build
        run: |
          curl -sL https://git.io/goreleaser | bash -s -- release --skip-publish --rm-dist
          rm -f dist/CHANGELOG.md dist/config.yaml
          ls -al dist/
      -
        name: Deploy
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go get -u github.com/tcnksm/ghr
          ghr --version
          ghr -n ${TAG_NAME} -draft ${TAG_NAME} dist/
