name: Release

on:
  create:
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.12.4
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Build
        run: curl -sL https://git.io/goreleaser | bash -s -- release --skip-publish --rm-dist
      -
        name: Deploy
        if: success()
        env:
          GHR_VERSION: v0.12.2
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -SLf https://github.com/tcnksm/ghr/releases/download/${GHR_VERSION}/ghr_${GHR_VERSION}_linux_amd64.tar.gz | tar xzC /usr/locl/bin --strip-components=1
          export TAG_NAME=$(jq --raw-output .ref "$GITHUB_EVENT_PATH")
          ls -al dist/
          go get -u github.com/tcnksm/ghr
          ghr -n ${TAGNAME} -draft ${TAGNAME} dist/
