name: Release

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.12.4
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Snapshot
        if: github.event != 'push'
        run: curl -sL https://git.io/goreleaser | bash -s -- release --snapshot --rm-dist
      -
        name: Release
        if: github.event == 'push'
        run: curl -sL https://git.io/goreleaser | bash -s -- release --skip-publish --rm-dist
