name: Snapshot

on:
  push:
    branches:
      - "*"
    tags:
      - "!*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.12.4
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Build
        run: curl -sL https://git.io/goreleaser | bash -s -- release --snapshot --rm-dist
